import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/_index.tsx"),
  route("auth", "routes/auth._index.tsx"),
  route("auth/:provider", "routes/auth.oauth.tsx"),
  route("auth/:provider/callback", "routes/auth.oauth.callback.tsx"),
  route("auth/logout.html", "routes/auth.logout[.]html.tsx"),
  route("contact.html", "routes/contact[.]html.tsx"),
  route("links", "routes/links._index.tsx"),
  route("links/add.html", "routes/links.add[.]html.tsx"),
  route("links/archive", "routes/links.archive._index.tsx"),
  route("links/archive/:year", "routes/links.archive.$year._index.tsx"),
  route("links/backup.json", "routes/links.backup[.]json.tsx"),
  route("links/delete.html", "routes/links.delete[.]html.tsx"),
  route("links/edit.html", "routes/links.edit[.]html.tsx"),
  route("links/import-feed.html", "routes/links.import-feed[.]html.tsx"),
  route("links/import-json.html", "routes/links.import-json[.]html.tsx"),
  route("links/tags.html", "routes/links.tags[.]html.tsx"),
  route("links/untagged.html", "routes/links.untagged[.]html.tsx"),
  route("patterns", "routes/patterns._index.tsx"),
  route("patterns/:entry", "routes/patterns.$entry._index.tsx"),
  route("patterns/tags.html", "routes/patterns.tags[.]html.tsx"),
  route("search.html", "routes/search[.]html.tsx"),
  route("sharing", "routes/sharing._index.tsx"),
  route("sharing/lookup.json", "routes/sharing.lookup[.]json.ts"),
  route("sharing/new.json", "routes/sharing.new[.]json.tsx"),
  route("sitemap.xml", "routes/sitemap[.]xml.tsx"),
  route("status.json", "routes/status[.]json.tsx"),
  route("testing", "routes/testing._index.tsx"),
] satisfies RouteConfig;
